version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network

  webapp:
    build:
      context: ./path/to/angular_app
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "3200:3200"  # Map Angular app's port 3200 to host
    depends_on:
      - elasticsearch
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
